# Generated by Django 5.2.4 on 2025-07-23 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0002_loginactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
